### ISSUE TITLE
Testing reaction core with velocity

### ISSUE THREAD

**Issue by boboci9** [reactioncommerce/reaction-core#57]
Hi,

Do you by any chance have any code using velocity server or client testing with reaction commerce package. I wrote some packages like search for products for reaction commerce and I wanted to write some velocity testing for my package but I can't seem to figure out how to create test products to spy on from velocity.

Thanks in advance very much.

**Comment by boboci9** [comment]
Hi, please let me know when you manage to do some tests, I am trying to create products in the testing (mirror) DB but I can't seem to add the tables and the schema yet.
Thank you in advance.

**Comment by ramusus** [comment]
Hi, I also very interested in testing of reaction-core by velocity. Yesterday I started to write some code. I already done some schema factories using this apps:

```
dburles:factory
anti:fake
```

Please, let me know as well if you will do some work in this direction.

**Comment by aaronjudd** [comment]
@boboci9 just rereading your comment about the schema/db -> in meteor the collections don't get created until you actually insert something.  We have fixtures in the core code that creates the collections with test/default data if there aren't any records. (see fixture.coffee). 

@ramusus soon as we get v0.2.2 out the door, I'll start on working on some tests.

**Comment by ramusus** [comment]
I started to do some works on testing the project here https://github.com/ramusus/reaction-core/tree/v0.2.2_tests

And here is PR https://github.com/reactioncommerce/reaction-core/pull/72

**Comment by boboci9** [comment]
Thanks Aaron, I found that and it was very useful, however I also realized that when I get rid of all the errors and with this new update by Sanjo the mirror DB is populated with data.

**Comment by aaronjudd** [comment]
@ramusus I merged the tests pull requests.  Couple of thoughts - I changed the symlinks to use package names as cloned from github, so that you can checkout directly into packages, or symlink direct into package dir - naming doesn't matter there, as long as you use the name: key in the package declaration. 

Also saw that you added mocha and jasmine.  From the velocity docs: `We currently do not recommend installing both Jasmine and Mocha at the same time.`  Not sure what the results will be.  To me, velocity isn't really focused on package testing, but rather app testing. I've mentioned this before, and am not sure what's been done about this, but I sort of hate the fact that we have to add symlinks in the app, really tests existence should be automatically detected by velocity.  Perhaps we could add a bash script, or even a build plugin to detect packages with tests and add them at the app level.

**Comment by aaronjudd** [comment]
Move discussion to https://github.com/reactioncommerce/reaction/issues/241
